import { Funcionario } from './funcionarios';

export const FUNCIONARIOS_MOCK_DATA: Funcionario[] = [
  {
    id: 1,
    idade: 20,
    nome: 'Robinson',
    sobrenome: 'Jennings',
    empresa: 'Ludak',
    email: 'robinson.jennings@ludak.me',
  },
  {
    id: 2,
    idade: 40,
    nome: 'James',
    sobrenome: 'Porter',
    empresa: 'Zensor',
    email: 'james.porter@zensor.info',
  },
  {
    id: 3,
    idade: 24,
    nome: 'Shawna',
    sobrenome: 'Dejesus',
    empresa: 'Quintity',
    email: 'shawna.dejesus@quintity.biz',
  },
  {
    id: 4,
    idade: 27,
    nome: 'Ivy',
    sobrenome: 'Chavez',
    empresa: 'Kyaguru',
    email: 'ivy.chavez@kyaguru.co.uk',
  },
  {
    id: 5,
    idade: 34,
    nome: 'Graham',
    sobrenome: 'Rocha',
    empresa: 'Geekol',
    email: 'graham.rocha@geekol.com',
  },
  {
    id: 6,
    idade: 30,
    nome: 'Blankenship',
    sobrenome: 'Fulton',
    empresa: 'Myopium',
    email: 'blankenship.fulton@myopium',
  },
  {
    id: 7,
    idade: 27,
    nome: 'Benjamin',
    sobrenome: 'Nicholson',
    empresa: 'Endipin',
    email: 'benjamin.nicholson@endipin.us',
  },
  {
    id: 8,
    idade: 35,
    nome: 'Charles',
    sobrenome: 'Harrington',
    empresa: 'Earbang',
    email: 'charles.harrington@earbang.biz',
  },
  {
    id: 9,
    idade: 39,
    nome: 'Mullen',
    sobrenome: 'Bennett',
    empresa: 'Progenex',
    email: 'mullen.bennett@progenex.tv',
  },
  {
    id: 10,
    idade: 38,
    nome: 'Vazquez',
    sobrenome: 'Lindsey',
    empresa: 'Nimon',
    email: 'vazquez.lindsey@nimon.net',
  },
  {
    id: 11,
    idade: 38,
    nome: 'Laurel',
    sobrenome: 'Berger',
    empresa: 'Turnabout',
    email: 'laurel.berger@turnabout.ca',
  },
  {
    id: 12,
    idade: 41,
    nome: 'Buckley',
    sobrenome: 'Price',
    empresa: 'Illumity',
    email: 'buckley.price@illumity.org',
  },
  {
    id: 13,
    idade: 58,
    nome: 'Alta',
    sobrenome: 'Castaneda',
    empresa: 'Zolavo',
    email: 'alta.castaneda@zolavo.me',
  },
  {
    id: 14,
    idade: 27,
    nome: 'Tamra',
    sobrenome: 'Wyatt',
    empresa: 'Diginetic',
    email: 'tamra.wyatt@diginetic.info',
  },
  {
    id: 15,
    idade: 36,
    nome: 'Sears',
    sobrenome: 'Nolan',
    empresa: 'Utarian',
    email: 'sears.nolan@utarian.biz',
  },
  {
    id: 16,
    idade: 34,
    nome: 'Arline',
    sobrenome: 'Goodwin',
    empresa: 'Deminimum',
    email: 'arline.goodwin@deminimum.co.uk',
  },
  {
    id: 17,
    idade: 27,
    nome: 'White',
    sobrenome: 'Bentley',
    empresa: 'Sealoud',
    email: 'white.bentley@sealoud.com',
  },
  {
    id: 18,
    idade: 35,
    nome: 'Guzman',
    sobrenome: 'Mitchell',
    empresa: 'Insectus',
    email: 'guzman.mitchell@insectus',
  },
  {
    id: 19,
    idade: 24,
    nome: 'Ford',
    sobrenome: 'Boyle',
    empresa: 'Buzzness',
    email: 'ford.boyle@buzzness.us',
  },
  {
    id: 20,
    idade: 31,
    nome: 'George',
    sobrenome: 'Glover',
    empresa: 'Isopop',
    email: 'george.glover@isopop.biz',
  },
  {
    id: 21,
    idade: 28,
    nome: 'Georgette',
    sobrenome: 'Barr',
    empresa: 'Webiotic',
    email: 'georgette.barr@webiotic.tv',
  },
  {
    id: 22,
    idade: 25,
    nome: 'Vera',
    sobrenome: 'Randall',
    empresa: 'Kindaloo',
    email: 'vera.randall@kindaloo.net',
  },
  {
    id: 23,
    idade: 36,
    nome: 'Walter',
    sobrenome: 'Hebert',
    empresa: 'Xoggle',
    email: 'walter.hebert@xoggle.ca',
  },
  {
    id: 24,
    idade: 32,
    nome: 'Townsend',
    sobrenome: 'Dyer',
    empresa: 'Tetak',
    email: 'townsend.dyer@tetak.org',
  },
  {
    id: 25,
    idade: 20,
    nome: 'Peggy',
    sobrenome: 'Bird',
    empresa: 'Permadyne',
    email: 'peggy.bird@permadyne.me',
  },
  {
    id: 26,
    idade: 22,
    nome: 'Nunez',
    sobrenome: 'Underwood',
    empresa: 'Talae',
    email: 'nunez.underwood@talae.info',
  },
  {
    id: 27,
    idade: 27,
    nome: 'Madden',
    sobrenome: 'Espinoza',
    empresa: 'Mantro',
    email: 'madden.espinoza@mantro.biz',
  },
  {
    id: 28,
    idade: 28,
    nome: 'Palmer',
    sobrenome: 'Banks',
    empresa: 'Zolarity',
    email: 'palmer.banks@zolarity.co.uk',
  },
  {
    id: 29,
    idade: 36,
    nome: 'Buck',
    sobrenome: 'Case',
    empresa: 'Ecraze',
    email: 'buck.case@ecraze.com',
  },
  {
    id: 30,
    idade: 25,
    nome: 'Bonner',
    sobrenome: 'Slater',
    empresa: 'Panzent',
    email: 'bonner.slater@panzent',
  },
  {
    id: 31,
    idade: 25,
    nome: 'Karla',
    sobrenome: 'Foreman',
    empresa: 'Stucco',
    email: 'karla.foreman@stucco.us',
  },
  {
    id: 32,
    idade: 28,
    nome: 'Peterson',
    sobrenome: 'Bonner',
    empresa: 'Rooforia',
    email: 'peterson.bonner@rooforia.biz',
  },
  {
    id: 33,
    idade: 27,
    nome: 'Haley',
    sobrenome: 'Tyson',
    empresa: 'Bovis',
    email: 'haley.tyson@bovis.tv',
  },
  {
    id: 34,
    idade: 40,
    nome: 'Ofelia',
    sobrenome: 'Mullen',
    empresa: 'Earthplex',
    email: 'ofelia.mullen@earthplex.net',
  },
  {
    id: 35,
    idade: 39,
    nome: 'Nadia',
    sobrenome: 'Blevins',
    empresa: 'Viocular',
    email: 'nadia.blevins@viocular.ca',
  },
  {
    id: 36,
    idade: 26,
    nome: 'Gracie',
    sobrenome: 'Dickerson',
    empresa: 'Zedalis',
    email: 'gracie.dickerson@zedalis.org',
  },
  {
    id: 37,
    idade: 22,
    nome: 'Conley',
    sobrenome: 'Mcneil',
    empresa: 'Enomen',
    email: 'conley.mcneil@enomen.me',
  },
  {
    id: 38,
    idade: 28,
    nome: 'Aguilar',
    sobrenome: 'Franklin',
    empresa: 'Combot',
    email: 'aguilar.franklin@combot.info',
  },
  {
    id: 39,
    idade: 25,
    nome: 'Lindsay',
    sobrenome: 'Christensen',
    empresa: 'Poochies',
    email: 'lindsay.christensen@poochies.biz',
  },
  {
    id: 40,
    idade: 35,
    nome: 'Gallagher',
    sobrenome: 'Petersen',
    empresa: 'Enersave',
    email: 'gallagher.petersen@enersave.co.uk',
  },
  {
    id: 41,
    idade: 29,
    nome: 'Sullivan',
    sobrenome: 'Mayer',
    empresa: 'Pathways',
    email: 'sullivan.mayer@pathways.com',
  },
  {
    id: 42,
    idade: 33,
    nome: 'Tami',
    sobrenome: 'Jacobson',
    empresa: 'Comtour',
    email: 'tami.jacobson@comtour',
  },
  {
    id: 43,
    idade: 23,
    nome: 'Josefina',
    sobrenome: 'Villarreal',
    empresa: 'Waab',
    email: 'josefina.villarreal@waab.us',
  },
  {
    id: 44,
    idade: 28,
    nome: 'Barbra',
    sobrenome: 'Burke',
    empresa: 'Cinesanct',
    email: 'barbra.burke@cinesanct.biz',
  },
  {
    id: 45,
    idade: 35,
    nome: 'Mccoy',
    sobrenome: 'Compton',
    empresa: 'Quotezart',
    email: 'mccoy.compton@quotezart.tv',
  },
  {
    id: 46,
    idade: 37,
    nome: 'Kristi',
    sobrenome: 'Frazier',
    empresa: 'Geekular',
    email: 'kristi.frazier@geekular.net',
  },
  {
    id: 47,
    idade: 22,
    nome: 'Elaine',
    sobrenome: 'Davis',
    empresa: 'Yurture',
    email: 'elaine.davis@yurture.ca',
  },
  {
    id: 48,
    idade: 34,
    nome: 'Hayden',
    sobrenome: 'Jordan',
    empresa: 'Musanpoly',
    email: 'hayden.jordan@musanpoly.org',
  },
  {
    id: 49,
    idade: 25,
    nome: 'Susie',
    sobrenome: 'Spears',
    empresa: 'Providco',
    email: 'susie.spears@providco.me',
  },
  {
    id: 50,
    idade: 47,
    nome: 'Morrison',
    sobrenome: 'Quinn',
    empresa: 'Kiggle',
    email: 'morrison.quinn@kiggle.info',
  },
  {
    id: 51,
    idade: 27,
    nome: 'Schroeder',
    sobrenome: 'Hale',
    empresa: 'Zepitope',
    email: 'schroeder.hale@zepitope.biz',
  },
  {
    id: 52,
    idade: 22,
    nome: 'Summer',
    sobrenome: 'Mccarty',
    empresa: 'Rockyard',
    email: 'summer.mccarty@rockyard.co.uk',
  },
  {
    id: 53,
    idade: 38,
    nome: 'Diana',
    sobrenome: 'Sims',
    empresa: 'Zilodyne',
    email: 'diana.sims@zilodyne.com',
  },
];
